# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.2.0-slim as base
WORKDIR /usr/src/app

# update packages (bun?)
RUN apt-get update -y && apt-get install -y

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS development
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV=development
ENV ENVIRONMENT=development

# run the app
# ports specified in Compose file
CMD [ "bun", "--bun", "--hot", "src/index.ts" ]
