name: lichess-slack-bot

services:
  app:
    container_name: app        
    # Warning: this isn't shared when extending
    depends_on:
      - store
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public

  store:
    container_name: dragonfly-store
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: on-failure
    ulimits:
        memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://stackoverflow.com/questions/56582446/how-to-use-host-network-for-docker-compose/56586535#56586535
    volumes:
      - storedata:/data

volumes:
  storedata:
